Update fully qualified role name
After update molecule to version 3.5.1,

  molecule 3.5.1 using python 3.9
      ansible:2.9.26
      delegated:3.5.1 from molecule
      docker:1.0.2 from molecule_docker requiring collections: community.docker>=1.8.0

the following error was shown:

  ERROR    Computed fully qualified role name of role-website does not follow current galaxy requirements.
  Please edit meta/main.yml and assure we can correctly determine full role name:

  galaxy_info:
  role_name: my_name  # if absent directory name hosting role is used instead
  namespace: my_galaxy_namespace  # if absent, author is used instead

  Namespace: https://galaxy.ansible.com/docs/contributing/namespaces.html#galaxy-namespace-limitations
  Role: https://galaxy.ansible.com/docs/contributing/creating_role.html#role-names

  As an alternative, you can add 'role-name' to either skip_list or warn_list.

  Traceback (most recent call last):
  [...]
  ansible_compat.errors.InvalidPrerequisiteError: Computed fully qualified role name of role-website does not follow current galaxy requirements.
  Please edit meta/main.yml and assure we can correctly determine full role name:

While at it updated company name and set a namespace.

We currently only support Debian/buster (Debian 10).

Documentation for the role metadata: https://galaxy.ansible.com/docs/contributing/creating_role.html#role-metadata